# Generated by Django 4.1.6 on 2023-03-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hast_tag',
            new_name='hash_tag',
        ),
    ]
