# Generated by Django 4.1.6 on 2023-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_hast_tag_post_hash_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/logo.jpg', upload_to='post_images/'),
        ),
    ]
