# Generated by Django 4.1.6 on 2023-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_email_address', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_subscribed',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('draft', 'Add to Draft'), ('posted & added to trending', 'Posted & Add to Trending')], default='posted', max_length=26),
        ),
    ]
