# Generated by Django 4.1.6 on 2023-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_newsletter_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Who_Visted_Your_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(editable=False, unique=True)),
                ('date_visted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
