# Generated by Django 4.1.6 on 2023-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_people_who_visted_your_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleWhoVistedYourSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('date_visted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='People_Who_Visted_Your_Site',
        ),
    ]
