# Generated by Django 4.1.6 on 2023-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('subject', models.CharField(editable=False, max_length=100)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('phone', models.CharField(editable=False, max_length=16)),
                ('message', models.TextField(editable=False)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-date_received',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('draft', 'Add to Draft')], default='posted', max_length=26),
        ),
    ]
