# Generated by Django 4.1.6 on 2023-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_receivedmail_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
